In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats as stats
import statistics

# 1. Load Car93 Data set

In [2]:
cars=pd.read_csv(r"C:\Users\patil\Desktop\Know IT CADC\Adv Analytics\Datasets\Cars93.csv")
cars

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8        25   
1         Acura   Legend  Midsize       29.2   33.9       38.7        18   
2          Audi       90  Compact       25.9   29.1       32.3        20   
3          Audi      100  Midsize       30.8   37.7       44.6        19   
4           BMW     535i  Midsize       23.7   30.0       36.2        22   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7        17   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4        21   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7        18   
91        Volvo      240  Compact       21.8   22.7       23.5        21   
92        Volvo      850  Midsize       24.8   26.7       28.5        20   

    MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0            31                None      Front  ...               13.2   
1            25  Driver & Passenger      Front  ...               18.0   
2            26         Driver only      Front  ...               16.9   
3            26  Driver & Passenger      Front  ...               21.1   
4            30         Driver only       Rear  ...               21.1   
..          ...                 ...        ...  ...                ...   
88           21                None      Front  ...               21.1   
89           30                None      Front  ...               18.5   
90           25                None      Front  ...               18.5   
91           28         Driver only       Rear  ...               15.8   
92           28  Driver & Passenger      Front  ...               19.3   

    Passengers  Length  Wheelbase  Width Turn.circle  Rear.seat.room  \
0            5     177        102     68          37            26.5   
1            5     195        115     71          38            30.0   
2            5     180        102     67          37            28.0   
3            6     193        106     70          37            31.0   
4            4     186        109     69          39            27.0   
..         ...     ...        ...    ...         ...             ...   
88           7     187        115     72          38            34.0   
89           5     180        103     67          35            31.5   
90           4     159         97     66          36            26.0   
91           5     190        104     67          37            29.5   
92           5     184        105     69          38            30.0   

    Luggage.room  Weight   Origin  
0           11.0    2705  non-USA  
1           15.0    3560  non-USA  
2           14.0    3375  non-USA  
3           17.0    3405  non-USA  
4           13.0    3640  non-USA  
..           ...     ...      ...  
88           NaN    3960  non-USA  
89          14.0    2985  non-USA  
90          15.0    2810  non-USA  
91          14.0    2985  non-USA  
92          15.0    3245  non-USA  

[93 rows x 26 columns]

# 2 using crosstab for AirBags and Type atrribute


In [3]:
crosstab_col=pd.crosstab(index=cars['AirBags'],columns=cars['Type'])
crosstab_col

Type                Compact  Large  Midsize  Small  Sporty  Van
AirBags                                                        
Driver & Passenger        2      4        7      0       3    0
Driver only               9      7       11      5       8    3
None                      5      0        4     16       3    6

# 3. calculate marginal probability for Driver & Passenger,Driver only,None

In [4]:
from scipy.stats.contingency import margins

In [5]:
x , y = margins(crosstab_col)

In [6]:
x

array([[16],
       [43],
       [34]], dtype=int64)

In [7]:
y

array([[16, 11, 22, 21, 14,  9]], dtype=int64)

In [8]:
mar_prb=[]
for i in x:
    prb = i/sum(x)
    mar_prb.append(prb)
mar_prb

[array([0.17204301]), array([0.46236559]), array([0.3655914])]

In [9]:
sum(mar_prb)

array([1.])

# 4. calculate marginal probability for Compact , Large , Midsize , Small , Sporty , Van

In [10]:
mar_prb=[]
for i in y:
    prb = i/sum(y[0])    # 0^th row of y
    mar_prb.append(prb)
print(mar_prb)


mar_prb=[]
for i in y:
    prb = i/sum(x)    # X only has 0^th index
    mar_prb.append(prb)
print(mar_prb)

[array([0.17204301, 0.11827957, 0.23655914, 0.22580645, 0.15053763,
       0.09677419])]
[array([0.17204301, 0.11827957, 0.23655914, 0.22580645, 0.15053763,
       0.09677419])]


In [11]:
print(mar_prb)
mar_prb=np.transpose(mar_prb)
print(mar_prb)
sum(mar_prb)

[array([0.17204301, 0.11827957, 0.23655914, 0.22580645, 0.15053763,
       0.09677419])]
[[0.17204301]
 [0.11827957]
 [0.23655914]
 [0.22580645]
 [0.15053763]
 [0.09677419]]


array([1.])

# 5. Load min_telcom Data Set 

In [12]:
min_tel=pd.read_csv(r"C:\Users\patil\Desktop\Know IT CADC\Adv Analytics\Datasets\mini_telcom.csv")
min_tel

Gender  TT_gt_100    Response 
0    male         y   not bought 
1    male         n   not bought 
2  female         n   not bought 
3  female         n   not bought 
4    male         n   not bought 
5    male         n   not bought 
6    male         y       bought 
7  female         y       bought 
8  female         n       bought 
9  female         y       bought

# 6. Calculate Marginal probability for Gender

In [15]:
print(min_tel.columns)
crosstab_col=pd.crosstab(index=min_tel['Response '],columns=min_tel['Gender '])
crosstab_col

Index(['Gender ', 'TT_gt_100', 'Response '], dtype='object')


Gender       female   male 
Response                   
bought             3      1
not bought         2      4

In [17]:
x , y =margins(crosstab_col)
y

array([[5, 5]], dtype=int64)

In [23]:
mar_prb=[]
y=y.T    # y.T is used to Transpose y array
for i in y:
    prb=i/sum(y)
    mar_prb.append(prb)
mar_prb

[array([0.5]), array([0.5])]

# 7. calculate the Marginal Probability for bought and not bought

In [24]:
mar_prb=[]
for i in x:
    prb=i/sum(x)
    mar_prb.append(prb)
mar_prb

[array([0.4]), array([0.6])]

# 8. Load Salaries data set

In [25]:
salaries=pd.read_csv(r"C:\Users\patil\Desktop\Know IT CADC\Adv Analytics\Datasets\Salaries.csv")
salaries

rank discipline  yrs.since.phd  yrs.service   sex  salary
0        Prof          B             19           18  Male  139750
1        Prof          B             20           16  Male  173200
2    AsstProf          B              4            3  Male   79750
3        Prof          B             45           39  Male  115000
4        Prof          B             40           41  Male  141500
..        ...        ...            ...          ...   ...     ...
392      Prof          A             33           30  Male  103106
393      Prof          A             31           19  Male  150564
394      Prof          A             42           25  Male  101738
395      Prof          A             25           15  Male   95329
396  AsstProf          A              8            4  Male   81035

[397 rows x 6 columns]

# 9. create cross tab on discipline and rank

In [27]:
crosstab_col=pd.crosstab(salaries['discipline'] , salaries['rank'])
crosstab_col

rank        AssocProf  AsstProf  Prof
discipline                           
A                  26        24   131
B                  38        43   135

# 10. Calculate conditional probability of AssocProf for each rank

In [39]:
# To calculate conditional probability we use iloc for specific location
val=crosstab_col.iloc[0,0]
col=crosstab_col.iloc[:,0].values.sum()
v1=val/col
v1

0.40625

In [40]:
val=crosstab_col.iloc[1,0]
col=crosstab_col.iloc[:,0].values.sum()
v2=val/col
v2

0.59375

In [41]:
v1+v2

1.0

# 11. load the HR_comma_sep data set

In [42]:
HR=pd.read_csv(r"C:\Users\patil\Desktop\Know IT CADC\Adv Analytics\Datasets\HR_comma_sep.csv")
HR

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years Department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14994                      0    support     low  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  

[14999 rows x 10 columns]